name: Java CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        with:
          ref: main
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
               
      - name: Build with Maven
        run: mvn clean package
        
      - name: Generate Jacoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
         generate-branches-badge: true
         jacoco-csv-file: >
          easy-rules-core/target/site/jacoco/jacoco.csv
          easy-rules-jexl/target/site/jacoco/jacoco.csv
          easy-rules-mvel/target/site/jacoco/jacoco.csv
          easy-rules-spel/target/site/jacoco/jacoco.csv
          easy-rules-support/target/site/jacoco/jacoco.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"       

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/
